### ISSUE TITLE
Retrofit CodeGen : @Path must be before @Query

### ISSUE THREAD

**Issue by vsouhrada** [eManPrague/swagger-codegen#11]
With Retrofit codegen we have an issue with retrofit in case of that we have URL which contains @Path and @Query params. @Query cannot be before @path in the Retrofit (see [implementation](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/RequestFactory.java#L376))

```
    java.lang.IllegalArgumentException: A @Path parameter must not come after a @Query. (parameter #2)
        for method MapItemApi.getMapItemMa
        at retrofit2.Utils.methodError(Utils.java:52)
        at retrofit2.Utils.methodError(Utils.java:42)
        at retrofit2.Utils.parameterError(Utils.java:61)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:376)
        at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:306)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:193)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy15.getMapItemMa(Unknown Source)
```

In the Java it is done by sorting params [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L344)

**Comment by shanselm-ergon** [comment]
Same problem here, I'll create a pull request for it.
